spring:
  datasource:
    url: jdbc:mysql://192.168.1.115:3306/enc_test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: 123456
#mybatis-plus:
#  type-handlers-package: top.niyihua.enc.secret #刚才编写的handler的位置
#  type-aliases-package: top.niyihua.enc.secret
